### PR TITLE
Update pom.xml to use src/main/resources

### PR DESCRIPTION
**Pull request by NimJay**
### Background 
* The `<resources>` element inside the `pom.xml` file tells the project (`balancereader` microservice in this case) where its [project resources](https://maven.apache.org/plugins/maven-resources-plugin/examples/resource-directory.html) are. Project resources includes the [`application.properties` file](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/release/v0.6.1/src/ledger/balancereader/src/main/resources/application.properties).
* Currently, the `pom.xml` points to `src/` while the `application.properties` file exists in the `src/main/resources` folder.
* So the `balancereader` never picks up on its [`application.properties` file](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/release/v0.6.1/src/ledger/balancereader/src/main/resources/application.properties).
* This issue also exists in `ledgerwriter`, and `transactionhistory`.

### Change Summary
* Update the `pom.xml` file of `balancereader`, `ledgerwriter`, and `transactionhistory` to pick up on the application.properties file in the `src/main/resources` folder.

### Additional Notes
* See https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1794 for evidence that the `balancereader` never picks up on the `application.properties` file.
     * In that pull-request, I first [changed the `{PORT}` value](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1794/commits/2e1b3d27f91ca1d4325f1b765a7f3ace00667fac) inside the `application.properties` file, without updating [the port in the K8s YAML of `balancereader`](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/src/ledger/balancereader/k8s/base/balancereader.yaml#L115). The change still successfully deployed — which it shouldn't have.
     * After that, I updated the `pom.xml` file to use `src/main/resources`. Then, deployment failed.

### Testing Procedure
* The GitHub check that deploys this change on a GKE cluster should suffice + the testing detailed in "Additional Notes", in my opinion.

### Related PRs or Issues 
* It's possible that https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/1354 is fixed by this pull-request.

### CODE REVIEW

**Comment by NimJay** [comment]
Looks like deployment of services was successful, but an end-to-end test failed:
```
fail... User can create account... duration":15518,"currentRetry":3 ... Timed out after waiting `10000ms` for your remote page to load.
```
It's likely some misconfiguration in one of the 3 `application.properties` files, but I will re-run the GitHub check to make sure it's not a flaky test.

**Comment by NimJay** [comment]
Now ready for review.

**Review by bourgeoisor — APPROVED** [review]
This LGTM.

iirc, Minikube (which was broken similarly to https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/1354) now works with this fix?

**Comment by bourgeoisor** [comment]
I assume https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1794 can also be closed?

**Pull request merged**
