### PR TITLE
Add strict mode to script

### PR DESCRIPTION
**Pull request by ahmetb**
Otherwise a failed command won't cause script to terminate.

### CODE REVIEW

**Comment by ahmetb** [comment]
So the smoke tests fail on `grep Aggregated` which is actually indicating a test issue (i.e. string not found). Tests need to be better in this case.

**Comment by Daniel-Sanche** [comment]
@ahmetb I re-ran the tests, so I can't see the previous error log. I opened https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/112, but this may become less relevant as we move to more robust UI tests (https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/53)

**Comment by ahmetb** [comment]
Feel free to merge as I don't have commit rights. :)

**Comment by ahmetb** [comment]
Yeah that makes sense. I think it simply was a timing issue.

**Pull request merged**
