### PR TITLE
[BREAKING CHANGES] Refactor of CI/CD, kustomize & skaffold

### PR DESCRIPTION
**Pull request by aablsk**
### Background 
Initially the fork that this PR is based on was created to showcase Google Cloud's CICD story encompassing Cloud Build / Cloud Deploy / kustomize / skaffold. Going further we implemented the current bank-of-anthos CI with Cloud Build, integrated pre- and post-deployment tests with skaffold for an attractive devX story from inner to outer loop.

### Change Summary
I'm still working on the change summary and link to a document including rationale for decisions.

### Additional Notes
Will add these while working on the change summary and rationales.

### Testing Procedure
Follow instructions in iac/tf-multienv-cicd-anthos-autopilot/README.md

### Related PRs or Issues 
[Previous PR including terraform infrastructure](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1006)

### CODE REVIEW

**Comment by aablsk** [comment]
This is not ready for review, yet - I'll add another comment when it is.

@bourgeoisor I'd like to also include bank-of-anthos specific configuration in this PR, which means I'd like to kindly ask for the projectId and region in which this will be deployed for internal use-cases.

**Comment by Amber3232433** [comment]
Hey can someone help ionnienevels308@gmail.com or biancanevels@at&t.com has been hacking me stealing money making API? Can any one help

**Comment by aablsk** [comment]
@bourgeoisor **The PR should now be ready for review.** 

**Caveats**
1) My last reproduction test was a week ago, unfortunately I cannot do another run before next month due to cost restrictions in my development environment. There should be no functional changes since my last test.
2) I'd kindly like to ask for special care when reviewing region tags, as I expect there will need to be some changes and I'm unsure about the envisioned target state.
3) The Github Actions-based deployment tests will fail, since it is using skaffold version previous to 2.0 which is incompatible with the new v4beta1 schema.

**Comment by Shabirmean** [comment]
@aablsk - Can you please resolve the conflicts on this PR?

**Comment by aablsk** [comment]
@Shabirmean Thanks for the ping, conflicts have been resolved ✅

**Comment by Amber3232433** [comment]
Once again, I do not agree to this 🧐

**Comment by bourgeoisor** [comment]
@aablsk Thank you! Would you be able to resolve the merge conflicts?

**Comment by Shabirmean** [comment]
@aablsk - Can you TAL at the conflicts on this PR? There seems to be more conflicts on the files changed in this PR!

**Comment by aablsk** [comment]
@Shabirmean Done! I merged current GoogleCloudPlatform/bank-of-anthos main into PR. Conflicts will continue to arise when there are changes to GoogleCloudPlatform/bank-of-anthos main.

**Comment by bourgeoisor** [comment]
@Shabirmean yes the plan is to do so this week.

**Review by bourgeoisor — APPROVED** [review]
LGTM

**Pull request merged**
