### PR TITLE
Bump skaffold to 2.7.1 in workflows

### PR DESCRIPTION
**Pull request by bourgeoisor**
This PR bumps the version of `skaffold` in the PR workflows to match the version in other workflows (`2.7.1`).

### CODE REVIEW

**Comment by NimJay** [comment]
The [`gcloud container fleet memberships get-credentials`](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/.github/workflows/ui-tests/run_for_env.sh#L22) command is failing.
```
ERROR: (gcloud.container.fleet.memberships.get-credentials) argument (MEMBERSHIP_NAME : --location=LOCATION): Must be specified.
Usage: gcloud container fleet memberships get-credentials (MEMBERSHIP_NAME : --location=LOCATION) [optional flags]
```
It looks like the [`ANTHOS_MEMBERSHIP `](https://cloud.google.com/deploy/docs/hooks#available_environment_variables) environment variable is unavailable.

**Comment by bourgeoisor** [comment]
Ran the build again, same error.

**Comment by bourgeoisor** [comment]
I've had to manually inject envs through a flag, since host env are not passed to `skaffold verify` since version 2.3 (see: https://github.com/GoogleContainerTools/skaffold/pull/8557)

**Review by NimJay — APPROVED** [review]
Looks good. Approved! Nice work tracing the issue.
I assume you've preserved the `set -x` commands intentionally — which I also approve (since I _believe_ there isn't a significant penalty for including them and it will be very helpful for debugging future issues).

**Pull request merged**
