### PR TITLE
Updated to Cloud SQL Proxy v2

### PR DESCRIPTION
**Pull request by arueth**
### Background/Change Summary
- Updated to Cloud SQL Proxy v2 in preparation for some upcoming fleet workload identity work

### Testing Procedure
Tested in my project using https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/docs/ci-cd-pipeline.md
- [dev](http://34.82.215.65)
- [staging](http://34.83.32.172)
- [prod](https://boa.prod.rueth.io)

### CODE REVIEW

**Comment by bourgeoisor** [comment]
@arueth currently (or at least last I tried), Bank of Anthos could juuuust fit in a 3-node default config GKE Standard cluster. This PR bumps a lot of requests upwards (sometimes 2x or 3x). What do you think is the new requirement if deploying in a GKE Standard cluster with these changes?

**Comment by arueth** [comment]
So this is the new configuration running in my environment
Screenshot 2023-08-14 9 16 02 AM

**Comment by bourgeoisor** [comment]
The reason I mention this is because there's a lot of learning content that leverages Bank of Anthos' default configs which still uses GKE Standard with a limited # of nodes (e.g. 3 or 4). If we bump the default base requests that may break that learning content.

For example, this tutorial deploys default Bank of Anthos on a 4-node cluster: https://cloud.google.com/migrate/containers/docs/migrating-monolith-vm-overview-setup#deploy

You can see a more complete list here: go/boa-usage (internal)

What do you think?

**Comment by arueth** [comment]
Are the skaffold changes and kubernetes-manifests folders kept synchronized? I believe the vast majority of tutorials outside of the docs in the repo use the kubernetes-manifests folder, is that correct?

**Comment by bourgeoisor** [comment]
Correct! 90+% of tutorials don't use kustomize / skaffold, they just `kubectl apply -f` the `kubernetes-manifests/` directory.

The sync is made at release time (new release of Bank of Anthos) where we `skaffold render`

https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/docs/releasing/make-release.sh#L58-L72

**Comment by bourgeoisor** [comment]
Yes, `kubernetes-manifests/` is essentially the barebone development profile (no Cloud SQL, low resources needed, etc)

How about we make the higher-resources-requests changes on the staging/production profiles like you're suggesting? That way the development profile (and by extension, the generated "barebones" k8s manifests) stay minimal

**Comment by arueth** [comment]
Since the Autopilot minimums are going to change, I'm changing this to only include the Cloud SQL Proxy v2 changes.

**Review by bourgeoisor — APPROVED** [review]
LGTM!

**Pull request merged**
