### PR TITLE
Implement ASM / Istio Integration & associated examples and documentation

### PR DESCRIPTION
**Pull request by benjamin-maynard**
This Pull Request is to extend the Bank of Anthos demo and implement a deployment option that works with Anthos Service Mesh/Istio.

Key changes are as follows:
* Implements a new alternative set of manifests at `/kubernetes-manifests-asm` that deploy the Bank of Anthos with the appropriate ASM Resources (Gateway and Virtual Service instead of Service w/ LoadBalancer, Virtual Service and DestinationRule for all of the BoA components) - See `./kubernetes-manifests-asm/README.md` for a full list of differences between the standard manifests and the ASM manifests.
* Updates the existing documentation to reflect that there is an option to deploy with ASM (see `./kubernetes-manifests-asm/README.md` & `./README.md`
* Implements some examples of how you can utilise ASM with the Bank of Anthos - including Fault Injection and deploying a new version and Traffic Shifting. More examples will follow in a subsequent PR.
* Updates the `src/frontend` application to accept a new environment variable `BANK_NAME` which is shown in the NavBar of all pages. This is used as part of the example when deploying a new version of the application. It defaults to the existing `Bank of Anthos` value if unset.

Happy to make any changes and discuss the proposed changes here.

### CODE REVIEW

**Comment by askmeegs** [comment]
Hi Benjamin, thanks for this PR. We are trying to keep this repo scoped to application code and basic YAML manifests. @Daniel-Sanche I think adding ASM/Istio manifests to this repo is fine (a basic VirtualService and Gateway for the frontend) but any text-based instructions or tutorials should live outside this repo - and ideally as a tutorial on cloud.google.com.

**Comment by askmeegs** [comment]
Also, thank you for the contribution to add `BANK_NAME`, I recommend that you make this a separate PR.

**Comment by Daniel-Sanche** [comment]
Thanks for the contribution! Our plan is to add additional manifests using kustomize overlays, rather than maintaining multiple deployment directories (go/boa-kustomize). We'll have to make some changes to match that pattern before merging. If you're willing to take that on that would be great, otherwise I'll make the addition when I have bandwidth

+1 on making a separate PR for `BANK_NAME` though, we could merge that one pretty quickly

**Comment by benjamin-maynard** [comment]
Thanks for the feedback @askmeegs @Daniel-Sanche.

Agree with your points. I'll get the `BANK_NAME` raised as a separate PR now. 

Happy to work with you on the Kustomize Overlays too. I'll spend some time reviewing the doc tomorrow.

**Comment by Daniel-Sanche** [comment]
I talked with @bharathkkb, who is working on a different branch that uses kustomize overlays, and it sounds like it might be best to hold off on this one until his is finalized to avoid conflicts. Are you alright with closing this PR for now, and we can revisit when the repo is ready to support it?

**Comment by benjamin-maynard** [comment]
Sure @Daniel-Sanche - Closing PR.

**Pull request closed without merging**
