### PR TITLE
Add ENV_PLATFORM environment variable to frontend

### LINKED ISSUE #137: Add ENV_PLATFORM flag to frontend / UI
Example - 

online-boutique-frontend-1

Setting the `ENV_PLATFORM` variable in the frontend manifest (gcp, aws, onprem, azure) updates a flag on the left side of the frontend. The flag changes colors based on environment. 
This will be useful for hybrid setups / if we distribute the frontend in multiple environments.

### PR DESCRIPTION
**Pull request by arueth**
### Background 
Added additional functionality to display the platform, similar to Online Boutique

### Change Summary
Added additional functionality to display the platform, similar to Online Boutique

### Testing Procedure
Tested locally with skaffold, currently running in my development environment:
http://35.230.47.88

Screenshot 2023-06-06 9 14 05 AM

### CODE REVIEW

**Comment by bourgeoisor** [comment]
Instead of taking the flag string outright, would it be possible to convert it to the real platform name, capitalized correctly?
e.g.:
- `gcp` would display `Google Cloud`
- `aws` would display `AWS`
- etc.

**Comment by arueth** [comment]
Yeah, it will just require another lookup. Do you want me to match the names displayed in online boutique?

**Comment by bourgeoisor** [comment]
Yeah might as well!
https://github.com/GoogleCloudPlatform/microservices-demo/blob/44692fa618ea5670e1291b3df58c8d673acbd9f8/src/frontend/handlers.go#L126C1-L146

**Review by bourgeoisor — APPROVED** [review]
LGTM-- Lots and lots of templating changes (thank you!)
I haven't meticulously looked at every changes but I'll trust our unit and UI tests. They're all passing, still!

**Comment by arueth** [comment]
Yeah I had to clean up the templates and move to some shared templates to DRY up the code, which then required fewer changes to implement the platform flag.

**Pull request merged**
